// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2a0koq7aTmu-1Qg7WPrUP8oTqrtgmpK8',
    appId: '1:1032097141063:web:fe2e98e8bd949c4593fc62',
    messagingSenderId: '1032097141063',
    projectId: 'xyz1-7039a',
    authDomain: 'xyz1-7039a.firebaseapp.com',
    storageBucket: 'xyz1-7039a.appspot.com',
    measurementId: 'G-V0V6JQ56JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3hJYXnPrP2uFk-D6b1qu7D47NyIV8sIY',
    appId: '1:1032097141063:android:c27b91e30d13974493fc62',
    messagingSenderId: '1032097141063',
    projectId: 'xyz1-7039a',
    storageBucket: 'xyz1-7039a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqrIDr20hQP6W4GJ8RHLIHbKtBMyDBudI',
    appId: '1:1032097141063:ios:ad764a7acaef704693fc62',
    messagingSenderId: '1032097141063',
    projectId: 'xyz1-7039a',
    storageBucket: 'xyz1-7039a.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqrIDr20hQP6W4GJ8RHLIHbKtBMyDBudI',
    appId: '1:1032097141063:ios:44647dcee996d1d393fc62',
    messagingSenderId: '1032097141063',
    projectId: 'xyz1-7039a',
    storageBucket: 'xyz1-7039a.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuth.RunnerTests',
  );
}
